### ISSUE TITLE
Consume boostorg/disjoint_sets

### ISSUE THREAD

**Issue by jeking3** [boostorg/graph#113]
The repository disjoint_sets contains one non-detail header and it is in boost/pending.  A search of boost shows that only Boost.Graph and Boost.GraphParallel use disjoint_sets.  I would like to eliminate disjoint_sets as a separate repository to ease the burden on the CMT.  The maintainer of Boost.Container did not feel that disjoint_sets belonged there.  As such I would like to move this module into Boost.Graph and update Graph and GraphParallel appropriately.

**Comment by anadon** [comment]
I'd be OK with this.  Could you submit a PR resolving this and your prior ticket for review?  I'm strapped on time right now so I won't be messing with this soon myself.

**Comment by jeking3** [comment]
It'll happen eventually.  I know how you feel!

**Comment by jeking3** [comment]
https://github.com/boostorg/graph/pull/169
