### ISSUE TITLE
9438-returns: call of overloaded ‘ignore_unused_variable_warning(...)’ is ambiguous

### ISSUE THREAD

**Issue by Magnati** [boostorg/graph#117]
Hello dear team of Boostorg.

First, I am not sure wheter this is the right repository to post this issue, if not, I will grandly repost it somewhere else.

The error is pretty much the same as in the closed issue [#9438](https://svn.boost.org/trac10/ticket/9438#no1) and I am not sure why it reappeared.

- OS: Ubuntu 18.04 Bionic Beaver
- clang: 6.0
- lemon: 1.3.1
- boost: happened under 1.63 and  was reproduced with boost 1.68

```c++
#include <boost/geometry.hpp>
#include <lemon/list_graph.h>

namespace bg = boost::geometry;
namespace bgi = boost::geometry::index;

using Point = boost::geometry::model::point<double, 2, bg::cs::cartesian>;
using Graph = lemon::ListDigraph;
using Node = lemon::ListDigraph::Node;
typedef std::pair<Point, Node> Pair;
using BoostRTree = bgi::rtree<Pair, bgi::quadratic<16>>;
using BoostQueryResult = std::vector<Pair>;

int main()
{
	Point one = Point(10, 51);
	Point two = Point(10, 51);
	BoostRTree rtreePair = BoostRTree();
	Graph graph;
	Node dummy1 = graph.addNode();
	Node dummy2 = graph.addNode();

	rtreePair.insert(std::make_pair(one, dummy1));	
	return 0;
}

```

**Comment by anadon** [comment]
I don't think graph is the right place for this.  It looks like you're actually looking for boost:geometry.

**Comment by anadon** [comment]
Let me know how that goes so I can let a proper maintainer close the ticket if that is the right place.

**Comment by Magnati** [comment]
I was at [boost/geometry](https://github.com/boostorg/geometry/issues/513#issuecomment-429272962) , now I am at [boost/range](https://github.com/boostorg/range/issues/78).
For now it seems that indeed `boost/graph` is not the right place.

**Comment by anadon** [comment]
@jzmaddock Close 'er out!
