### ISSUE TITLE
boost/detail/iterator.hpp is deprecated.

### ISSUE THREAD

**Issue by roccomoretti** [boostorg/graph#228]
As of Boost 1.74, the boost/detail/iterator.hpp header is deprecated and may print a warning message (`#pragma message: This header is deprecated. Use <iterator> instead.`)

The graph library directly uses the header in several locations:
* https://github.com/boostorg/graph/blob/develop/include/boost/graph/adjacency_iterator.hpp#L13
* https://github.com/boostorg/graph/blob/develop/include/boost/graph/incremental_components.hpp#L16
* https://github.com/boostorg/graph/blob/develop/include/boost/detail/algorithm.hpp#L33
 
This can results in a number of spurious compiler warning messages for people using the graph library.

(Issue encountered compiling with GCC 5.2 on Linux with -std=c++11, using the version tagged `boost-1.74.0`)

**Comment by thebrandre** [comment]
This issue still occurs in the current master branch for 1.75 (specifically, at commit 0c9dbd7808ef92dd14111b8a604ffd9860b42b51) when compiling with VS 2017.

**Comment by SpiritDogstar** [comment]
bump, running into this also.

**Comment by illfated** [comment]
Detailed message sample:
```
14>C:\local\boost_1_74_0\boost/range/result_iterator.hpp(20): message : This header is deprecated. Use <boost/range/iterator.hpp> instead.
14>C:\local\boost_1_74_0\boost/range/const_reverse_iterator.hpp(20): message : This header is deprecated. Use <boost/range/reverse_iterator.hpp> instead.
14>C:\local\boost_1_74_0\boost/range/reverse_result_iterator.hpp(20): message : This header is deprecated. Use <boost/range/reverse_iterator.hpp> instead.
```

**Comment by roccomoretti** [comment]
It looks like the merge of PR #218 fixed this issue. It wasn't merged in time to hit Boost 1.75, but I'm guessing it will be included when Boost 1.76 comes out.

**Comment by bullestock** [comment]
Does not appear to be fixed in Boost 1.76.0:

```
In file included from /opt/boost/1.76.0/include/boost/math/tools/cxx03_warn.hpp:9,
                 from /opt/boost/1.76.0/include/boost/math/constants/constants.hpp:11,
                 from /opt/boost/1.76.0/include/boost/geometry/util/math.hpp:30,
[...]
/opt/boost/1.76.0/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’```

**Comment by illfated** [comment]
That's a pity. I was hoping, but now it looks like we have to wait a version or two more before a solution is implemented.

**Comment by wolframroesler** [comment]
Can confirm the problem still exists in Boost 1.76.0. This in my source code:

```cpp
#include <boost/graph/adjacency_list.hpp>
```

produces the following message:

```
In file included from /usr/local/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/local/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/local/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/local/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/local/include/boost/property_map/vector_property_map.hpp:14,
                 from /usr/local/include/boost/property_map/property_map.hpp:602,
                 from /usr/local/include/boost/graph/adjacency_list.hpp:27,
                 from /home/wolfram/src/sdb/connector/cmdhdl/importbom.cpp:12:
/usr/local/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by TommyPec** [comment]
This bug is still there - on Boost  1.76.0. My humble suggestion is to not close a bug unless it's resolved.

**Comment by jeremy-murphy** [comment]
Could someone please test again on the latest version of Boost, and please be specific as to whether you are testing a packaged release or head of `master` or `develop`? According to the comments on the pull request, this looks like it should be in the latest packaged release. Thank you!

**Comment by phcerdan** [comment]
I recently compiled with release `1,78.0` and didn't get the warnings.

**Comment by jakobandersen** [comment]
Compiling from the packaged sources I get the warnings with 1.76 but neither with 1.77 nor 1.78.

**Comment by thomastrapp** [comment]
I got the deprecation warnings with Boost 1.76. But I do not get these warnings with Boost 1.78.

**Comment by wolframroesler** [comment]
No longer occurs for me with Boost 1.78.0.

**Comment by jeremy-murphy** [comment]
Great, thanks everyone, sounds conclusive.
