### ISSUE TITLE
Upgrading to 1.75.0 and hitting lots deprecated warnings for detail/iterator.hpp

### ISSUE THREAD

**Issue by nicsav** [boostorg/graph#245]
Hi all, I'm upgrading to 1.75.0 (from 1.59.0) and, even though I'm not directly including the offending file, I'm getting a lot of these warnings:

In file included from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/property_map/vector_property_map.hpp:14,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/property_map/property_map.hpp:602,
                 from /tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/graph/graphviz.hpp:19,
                 from /home/my/code/some.cpp:21:
/tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/detail/iterator.hpp:13:1: note: #pragma message: This header is deprecated. Use <iterator> instead.
   13 | BOOST_HEADER_DEPRECATED("<iterator>")
      | ^~~~~~~~~~~~~~~~~~~~~~~

It happens from various other boost headers (shared_pointer.hpp, depth_first_search.hpp, graph/adjacency_list.hpp, etc).

Oddly enough it does not happen for all places where, say shared_pointer.hpp, is included from my code. So, I'm a bit stumped.

I'm compiling with GCC9.1.0 in C++17 mode.

Any help appreciated,
Nick

**Comment by nicsav** [comment]
Yeah, I turned on g++ -M and it showed that graph/adjacency_iterator.hpp was included prior shared_ptr.hpp:

 /calypto/tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/graph/adjacency_iterator.hpp \
 /calypto/tools/install/boost/boost_1_75_0/rhel7/m64/include/boost/detail/iterator.hpp \

**Comment by jzmaddock** [comment]
This appears to now be fixed in master: apologies it didn't make 1.76, but will now be in 1.77.
