### ISSUE TITLE
Confusing call to `combine` in `astar_search_no_init_tree`

### ISSUE THREAD

**Issue by qbit86** [boostorg/graph#260]
What does this line of code mean in [astar_search.hpp](https://github.com/boostorg/graph/blob/d865589d62afba7ca590bfcaf76f0723f8494dd4/include/boost/graph/astar_search.hpp#L331)?
```cpp
combine(get(distance, v), e_weight);
```
The result of this `combine()` is not used anywhere. Actual distance update happens inside the `relax()` function.

**Comment by jeremy-murphy** [comment]
Agreed, that call to combine has no effect. I won't claim to totally understand the tree version of A*, but it looks like that line can simply be deleted.
