### ISSUE TITLE
[Question] Tested architectures for Linux

### ISSUE THREAD

**Issue by m-carrasco** [boostorg/graph#276]
Hi,

I am gathering information about which architectures are generally used by open-source projects for testing. After reading Boost Graph CI's code, I understand that for Linux testing _x86-64_ is the only tested architecture. Is this correct?

Thanks in advance!

Kind regards,
Manuel.

**Comment by jeremy-murphy** [comment]
Sounds about right.
This is not an _issue_, so I'm going to close it.
