### ISSUE TITLE
back edge is not visited in DFS order for self-loop vertex

### ISSUE THREAD

**Issue by Inori** [boostorg/graph#295]
When calling `boost::depth_first_search` on a graph which has one or more self-loop vertices, the `back_edge` callback will not get called in DFS order, seems it will be called when all other non-self-loop back edges are visited, this add some inconvenience.

**Comment by jeremy-murphy** [comment]
Why is it inconvenient?

It could be something to do with how the graph is constructed. Are the self loops always the last edge created from that particular source vertex? If possible, try creating them first?

It doesn't sound like incorrect behaviour, or is there something I'm missing?

**Comment by Inori** [comment]
In fact I'm trying to implement a compiler.
I think since the algorithm is called `depth_first_search`, then it should be best suit if vertex and edges belong to that vertex
are visited both in dfs order, such that I can implement scope stack more naturally, just pop the loop scope at back edges.
Delaying self-loop back edge visit seems unusual.
Of course with current behavior, I can also implement what I expect, but need more steps.
