### ISSUE TITLE
Strange errors deep in Boost.core libraries on old Xcode (7-10) platforms

### ISSUE THREAD

**Issue by jeremy-murphy** [boostorg/graph#298]
I accidentally overlooked these errors when I merged the fix for Stoer-Wagner, and I'm not sure whether it's easy to fix or not.
I'd rather keep the fix for the algorithm than support these old platforms, but the broader user-base may not agree.

See the failing builds here: https://drone.cpp.al/boostorg/graph/98/100/2

@sebrockm are you able to look at this? Presumably the fix you wrote has triggered it, so you're probably best suited to address it.

**Comment by sebrockm** [comment]
@jeremy-murphy Very strange indeed. I hope I can have a look soon.
I literally only copy pasted the old code and applied clang-format.
Note, that my PR has also some failed builds on Linux: https://drone.cpp.al/boostorg/graph/97
But now that it is merged, on master those Linux builds are passing and only some OSX builds are failing? 🤔 
Any idea how that can happen? Is CI on PRs slightly different from CI on master?

**Comment by pdimov** [comment]
```
../../../boost/type_traits/detail/has_binary_operator.hpp:68:96: error: no template named 'declval' in namespace 'std'; did you mean simply 'declval'?
      struct BOOST_JOIN(BOOST_TT_TRAIT_NAME, _dc_imp)<T, U, typename boost::make_void<decltype(std::declval<typename add_reference<T>::type>() BOOST_TT_TRAIT_OP std::declval<typename add_reference<U>::type>())>::type>
                                                                                               ^~~~~
../../../boost/type_traits/declval.hpp:40:44: note: 'declval' declared here
    typename add_rvalue_reference<T>::type declval() BOOST_NOEXCEPT; // as unevaluated operand
                                           ^
```
Looks like a straightforward bug in TypeTraits has_binary_operator: std::declval is being used without its header being included, which it shouldn't be anyway because it's C++11. The compiler suggestion of using boost::declval instead seems correct. An issue in TypeTraits should be opened about this, and someone should probably prepare a minimal test case.

**Comment by jzmaddock** [comment]
>Looks like a straightforward bug in TypeTraits has_binary_operator: std::declval is being used without its header being included, which it shouldn't be anyway because it's C++11. The compiler suggestion of using boost::declval instead seems correct. An issue in TypeTraits should be opened about this, and someone should probably prepare a minimal test case.

Nope, that branch in the code is for C++11 and up: `std::declval` should be present, and it's header - `<utility>` *is* being included.

**Comment by jeremy-murphy** [comment]
Thanks for your help, I'll close this and update the CI scripts accordingly.
