### ISSUE TITLE
Graphml: unnecessary dependency on graphviz (and thus Boost.Regex)

### ISSUE THREAD

**Issue by francoisk** [boostorg/graph#326]
## Context/background
We have [packaged](https://github.com/build2-packaging/boost) Boost for [build2](https://build2.org/) and are about to release changes that reduce the number of dependencies on Boost.Regex.

The way we have done this in our Boost.Graph package is to make the graphviz "submodule"---which is the only part that logically depends on Boost.Regex---optional and disabled by default. When it is disabled none of the graphviz-related headers are installed.

## The problem
However, `graphml.hpp` includes `graphviz.hpp`, making it impossible to disable graphviz without also disabling graphml, and this for nothing but a few exception structs.

## Suggested solution
Our package's [patch](https://github.com/build2-packaging/boost/commit/e6ff2e3acf123509827dcd0c23e934f893cfb765) breaks this dependency by moving these exception structs to `exception.hpp` (which already contains exceptions that look similar/related to the ones in question) and including `exception.hpp` from `graphml.hpp` and `graphviz.hpp`.

**Comment by jeremy-murphy** [comment]
Sounds great! Can you make a pull request with your patch here?

**Comment by jeremy-murphy** [comment]
That Boost.Regex dependency has been a pain for a while, but I haven't had time to look into it.

**Comment by boris-kolpackov** [comment]
> That Boost.Regex dependency has been a pain for a while, but I haven't had time to look into it.

FYI, the direct dependency on `Boost.Regex` is only half of the problem: a number of other dependencies (I see `Boost.Algorithm`, `Boost.Range`, and `Boost.Serialization` right away) will pull `Boost.Regex` indirectly. But it's a step in the right direction.

**Comment by jeremy-murphy** [comment]
That PR was merged, so does that resolve this particular issue?
