### ISSUE TITLE
unable to compile lengauer_tarjan_dominator_tree with compressed_sparse_row_graph/bidirectionalS 

### ISSUE THREAD

**Issue by marakew** [boostorg/graph#330]
the issue at concept restriction

https://github.com/boostorg/graph/blob/00028767d804fe3da20996afedf06f9eecfb5975/include/boost/graph/graph_concepts.hpp#L134
https://github.com/boostorg/graph/blob/00028767d804fe3da20996afedf06f9eecfb5975/include/boost/graph/graph_concepts.hpp#L142

i just remove it, and all compiled ok
so what wrong ?
i cant find any implementation "degree" for "compressed_sparse_row_graph"

**Comment by jeremy-murphy** [comment]
Ahh... I really don't know. I think you need to provide a lot more information about your build toolchain and environment, etc.

**Comment by marakew** [comment]
example
https://wandbox.org/permlink/7GQe1hlL1GR7SFgc
as you can see concept restriction
but dergee doest use at eny where

**Comment by jeremy-murphy** [comment]
So, there is a bidirectional specialization of CSRG, and it has `in_degree` and `out_degree` member functions, which I believe are all that is required to compute `degree(v, g)`, but maybe the free `degree` function definition is not included automatically?

Could you find where `degree` is defined and include that header file first, see if it fixes the compilation error?

**Comment by marakew** [comment]
function degree not exist for compressed_sparse_row_graph

**Comment by jeremy-murphy** [comment]
Could you dig a little deeper, please? There is a `boost::graph::degree(v, g)` function somewhere, the question is why doesn't it generically support CSRG?

**Comment by jeremy-murphy** [comment]
What was the solution?
