### ISSUE TITLE
broken link to example for reverse graph adaptor

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [boostorg/graph#358]
The link https://www.boost.org/doc/libs/1_84_0/libs/graph/example/reverse-graph-eg.cpp is broken in the docs

**Comment by jeremy-murphy** [comment]
Thanks, can you open a pull request to fix it?

**Comment by andrea-cassioli-maersk** [comment]
sure, but I have no clue how the docs are generated.

**Comment by andrea-cassioli-maersk** [comment]
never-mind, I got it.

**Comment by andrea-cassioli-maersk** [comment]
@jeremy-murphy how is the workflow? do you make PR directly here or via the full boost repo?

**Comment by jeremy-murphy** [comment]
Here.

**Comment by andrea-cassioli-maersk** [comment]
here we go https://github.com/boostorg/graph/pull/360
